[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'dense-analysis/ale'

[[plugins]]
repo = 'tpope/vim-abolish'

[[plugins]]
repo = 'kana/vim-submode'

[[plugins]]
repo = 'easymotion/vim-easymotion'

[[plugins]]
repo = 'junegunn/vim-easy-align'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-rhubarb'

[[plugins]]
repo = 'thinca/vim-quickrun'
rev = 'v0.8.0'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'vim-scripts/vim-auto-save'

[[plugins]]
repo = 'nazo/pt.vim'

[[plugins]]
repo = 'glidenote/memolist.vim'

[[plugins]]
repo = 'maxmellon/vim-jsx-pretty'

# for apply vim-jsx-pretty to tsx
[[plugins]]
repo = 'HerringtonDarkholme/yats.vim'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
merged = 0

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'

[[plugins]]
repo = 'mattn/vim-sqlfmt'

[[plugins]]
repo = 'neoclide/coc.nvim'
source = 'release'
build = 'coc#util#install()'

[[plugins]]
repo = 'github/copilot.vim'

[[plugins]]
repo = 'chrisbra/csv.vim'
